-- nvim-stagecoach: wraps the `stagecoach` CLI — non-blocking AI commit messages
-- generated by your coding-agent CLI (pi/claude/...), surfaced on the statusline.
--
-- Loaded from the LOCAL dev checkout. `dir` makes lazy use this working tree
-- directly on `runtimepath` (no clone, no build hook) — equivalent to the remote
-- here since origin/main and local are 0/0. Omitting `build` keeps the `dev`
-- `stagecoach` binary intact instead of `stagecoach upgrade --yes` replacing it.
-- To switch to the canonical GitHub install later: drop `dir`, add
--   build = function() require("stagecoach.build").run() end,
return {
	"dabstractor/nvim-stagecoach",
	dir = "~/projects/nvim-stagecoach",
	cmd = { "Stagecoach", "StagecoachUpdate", "StagecoachInstall" },
	-- Plugin ships no default keybind; this both binds <Leader><C-a> and lazy-loads on press.
	keys = {
		{ "<Leader><C-a>", "<cmd>Stagecoach<cr>", desc = "stagecoach: AI commit" },
	},
	opts = {}, -- lazy auto-calls require("stagecoach").setup({})
}